name: 删除旧的快照版本依赖

on:
  workflow_dispatch: # 支持手动触发
  schedule:
    - cron: '0 3 * * 0' # 每周日自动运行一次

permissions:
  packages: write
  contents: read

jobs:
  clean-packages:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package-name:
          - 'com.yzm.fireworks.fireworks-dependencies'
          - 'com.yzm.fireworks.fireworks-common-spring-boot-starter'
          - 'com.yzm.fireworks.fireworks-spring-boot-parent'
          - 'com.yzm.fireworks.fireworks-framework'
          - 'com.yzm.fireworks.fireworks-rest-client-spring-boot-starter'
          - 'com.yzm.fireworks.fireworks-msg-spring-boot-starter'
          - 'com.yzm.fireworks.fireworks-id-spring-boot-starter'
          - 'com.yzm.fireworks.fireworks-storage-spring-boot-starter'
          - 'com.yzm.fireworks.fireworks-api-spring-boot-starter'
          - 'com.yzm.fireworks.fireworks-redis-spring-boot-starter'
          - 'com.yzm.fireworks.fireworks-web-spring-boot-starter'
          - 'com.yzm.fireworks.fireworks-token-spring-boot-starter'
          - 'com.yzm.fireworks.fireworks-xxljob-spring-boot-starter'
          - 'com.yzm.fireworks.fireworks-export-spring-boot-starter'
          - 'com.yzm.fireworks.fireworks-saga-spring-boot-starter'
          - 'com.yzm.fireworks.fireworks-webflux-client-spring-boot-starter'
          # 这里填写你的其他 starter 名称...

    steps:
      - name: Delete older SNAPSHOT versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ matrix.package-name }}
          package-type: 'maven'
          # 针对每个 SNAPSHOT 构件只保留最新的 2 个
          min-versions-to-keep: 2

          # 【核心配置】正则表达式：
          # 1. ignore-versions：告诉 Action“跳过/保留”符合此正则的版本。
          # 2. 下面这个正则的意思是：除了包含 -SNAPSHOT 或时间戳格式的版本外，其他的（如 1.0.0, 1.0.1, v1.2.0 等正式 Tag）一律 Ignore（保留不删）！
          ignore-versions: '^(?!\d+\.\d+\.\d+.*-SNAPSHOT).*'

          token: ${{ secrets.GITHUB_TOKEN }}
